### ISSUE TITLE
 Already server running ?

### ISSUE THREAD

**Issue by MassMadankumar** [msyvr/RandomRuby#1]
root@instance-2:/mnt/zapstore.com/shopifyapp/zap# rails s
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.11.0 (ruby 2.4.2-p198), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop

**Comment by msyvr** [comment]
This seems to be for the puma repo. Closing.
